# Assignment

In [2]:
import numpy as np
import pandas as pd

# NUMPY

In [10]:
dict=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(dict)
print(arr)
arr*=2
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Dataframe

In [23]:
dict={"product_name":["A","B","C"],"price":[100,150,200],"stock_quantity":[45,50,60]}
df=pd.DataFrame(dict)
print(df)

  product_name  price  stock_quantity
0            A    100              45
1            B    150              50
2            C    200              60


# Filtering

In [28]:
print(df[df['stock_quantity']>50])

  product_name  price  stock_quantity
2            C    200              60
